# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedLifeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_added', models.IntegerField(default=0)),
                ('life_added_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeathNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.TextField()),
                ('cause_of_death', models.TextField(null=True)),
                ('datetime_of_death', models.DateTimeField(null=True)),
                ('entry_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='addedlifespan',
            name='deathnote_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ryuk.DeathNote'),
        ),
    ]
